#
# ğŸ›‘ Think twice before editing this file! ğŸ›‘
# âš ï¸ This file is maintained via https://github.com/IanStorm/dev-settings-sync. âš ï¸
#

# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Are dev settings synced?

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check-job:
    runs-on: ubuntu-22.04
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v4

      - name: Docker Pull
        run: docker pull ianstorm/dev-settings-sync

      - name: Docker Run check
        run: docker run -t -v ${PWD}/:/mnt/ ianstorm/dev-settings-sync check
